
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "D:/DevelopmentTool/mingw/mingw64/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:211 (message)"
      - "CMakeLists.txt:3 (project)"
    message: |
      The system is: Windows - 6.2.9200 - AMD64
...
